spring.application.name=mission
# spring.mvc.view.prefix=/WEB-INF/views/
# spring.mvc.view.suffix=.jsp

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:mariadb://localhost:3306/mydatabase
spring.datasource.username=clonecode
spring.datasource.password=bpointclone
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true